apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-analyzer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: mood-analyzer
    apps.tanzu.vmware.com/workload-type: dekt-worker
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-analyzer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: mood-analyzer
      apps.tanzu.vmware.com/workload-type: dekt-worker
      carto.run/workload-name: mood-analyzer
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-analyzer
        apps.tanzu.vmware.com/workload-type: dekt-worker
        carto.run/workload-name: mood-analyzer
    spec:
      containers:
      - image: registry.dekt.io/dekt-stage/mood-analyzer-dekt-apps@sha256:d6acca7fb947880857acb2603a952749f9432e07a23c958189b0a26c2c671dec
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

