apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mood-portal
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: mood-portal
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-portal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-portal
        apps.tanzu.vmware.com/workload-type: dekt-url
        carto.run/workload-name: mood-portal
    spec:
      containers:
      - image: dektregistry.azurecr.io/dekt-stage/mood-portal-dekt-apps@sha256:ef28d7cd76395ce256942bfd22a91ac30ac920f036e1280e61e671798653b631
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

