apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mood-portal
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: mood-portal
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-portal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-portal
        apps.tanzu.vmware.com/workload-type: dekt-url
        carto.run/workload-name: mood-portal
    spec:
      containers:
      - env:
        - name: SNIFF_LEVEL
          value: "1"
        - name: SENSORS_ACTIVATE_API
          value: http://mood-sensors.run.dekt.io/activate
        - name: SENSORS_MEASURE_API
          value: http://mood-sensors.run.dekt.io/measure
        image: registry.dekt.io/dekt-stage/mood-portal-dekt-apps@sha256:836cbf3a78c44b66ae92f85a9719d3e7c2a147507107c14f1a93ccbb91bea64c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

